/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import entidades.Asignacion_Traslado;
import entidades.Productor;
import entidades.Quimico;
import entidades.Residuo;
import entidades.Solicitud_de_Traslado;
import entidades.Transportador;
import entidades.Transporte;
import entidades.Usuario;
import entidades.Vehiculo;
import implementaciones.FNegocio;
import implementaciones.FabricaNegocios;
import implementaciones.INegocio;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import org.bson.types.ObjectId;

/**
 * Frame del menu principal.
 *
 * @author Equipo 1 Jose,Abraham y Oroz
 */
public class FPrincipal extends javax.swing.JFrame {

    private static FPrincipal principal;
    private INegocio negocio = FabricaNegocios.crearFNegocio();
    private Usuario usuarioR;

    /**
     * Creates new form Principal
     *
     */
    public FPrincipal() {
        initComponents();
    }

    /**
     * Método que sirve para activar o desactivar ciertos botones los cuales
     * cambiaran dependiendo del tipo de usuario que haya iniciado sesión
     *
     * @param tipo Tipo de usuario a establecer.
     * @param usuario Uusario a establecer.
     */
    public void botones(int tipo, Usuario usuario) {
        this.usuarioR = usuario;
//      this.jPanelTransporte.setVisible(true);
        this.jButtonRegistrarUsuarios.setEnabled(true);
        this.jButtonRegistrarEmpresas.setEnabled(true);
        this.jButtonAsignarTraslados.setEnabled(true);
        this.jButtonRegistrarResiduos.setEnabled(true);
        this.jButtonRegistrarQuimicos.setEnabled(true);
        this.jButtonRegistrarSolicitarTraslado.setEnabled(true);
        this.jButtonRegistrarTraslado.setEnabled(true);
        this.jButtonRegistrarVehiculos.setEnabled(true);
        switch (tipo) {
            case 1:
//              this.jPanelTransporte.setVisible(false);
                this.jButtonRegistrarResiduos.setEnabled(false);
                this.jButtonRegistrarQuimicos.setEnabled(false);
                this.jButtonRegistrarSolicitarTraslado.setEnabled(false);
                this.jButtonRegistrarTraslado.setEnabled(false);
                this.jButtonRegistrarVehiculos.setEnabled(false);
                break;
            case 2:
//                this.jPanelTransporte.setVisible(false);
                this.jButtonRegistrarUsuarios.setEnabled(false);
                this.jButtonRegistrarEmpresas.setEnabled(false);
                this.jButtonAsignarTraslados.setEnabled(false);
                this.jButtonRegistrarTraslado.setEnabled(false);
                this.jButtonRegistrarVehiculos.setEnabled(false);
                break;
            default:
//               this.jPanelProductor.setVisible(false);
                this.jButtonRegistrarUsuarios.setEnabled(false);
                this.jButtonRegistrarEmpresas.setEnabled(false);
                this.jButtonAsignarTraslados.setEnabled(false);
                this.jButtonRegistrarResiduos.setEnabled(false);
                this.jButtonRegistrarQuimicos.setEnabled(false);
                this.jButtonRegistrarSolicitarTraslado.setEnabled(false);
                break;
        }
    }

    /**
     * patrón Singleton para que nomas exista un frame de este tipo durante toda
     * la actividad de la aplicación
     *
     * @return Instancia del menu principal.
     */
    public static FPrincipal getInstance() {
        if (FPrincipal.principal != null) {
            return FPrincipal.principal;
        } else {
            FPrincipal.principal = new FPrincipal();
            return principal;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanelAdministrador = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonRegistrarEmpresas = new javax.swing.JButton();
        jButtonRegistrarUsuarios = new javax.swing.JButton();
        jButtonAsignarTraslados = new javax.swing.JButton();
        jPanelProductor = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonRegistrarResiduos = new javax.swing.JButton();
        jButtonRegistrarQuimicos = new javax.swing.JButton();
        jButtonRegistrarSolicitarTraslado = new javax.swing.JButton();
        jPanelTransporte = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButtonRegistrarTraslado = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButtonRegistrarVehiculos = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menú");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(698, 540));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Menú Principal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel12)
                .addContainerGap(263, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 690, 60);

        jPanelAdministrador.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Administrador");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Registrar Usuarios");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Registrar Empresas");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Asignar Taslados");

        jButtonRegistrarEmpresas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRegistrarEmpresas.setText("Entrar");
        jButtonRegistrarEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarEmpresasActionPerformed(evt);
            }
        });

        jButtonRegistrarUsuarios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRegistrarUsuarios.setText("Entrar");
        jButtonRegistrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarUsuariosActionPerformed(evt);
            }
        });

        jButtonAsignarTraslados.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAsignarTraslados.setText("Entrar");
        jButtonAsignarTraslados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsignarTrasladosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAdministradorLayout = new javax.swing.GroupLayout(jPanelAdministrador);
        jPanelAdministrador.setLayout(jPanelAdministradorLayout);
        jPanelAdministradorLayout.setHorizontalGroup(
            jPanelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdministradorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAdministradorLayout.createSequentialGroup()
                        .addGroup(jPanelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanelAdministradorLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanelAdministradorLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(117, 117, 117)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(71, 71, 71))))
            .addGroup(jPanelAdministradorLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButtonRegistrarUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRegistrarEmpresas)
                .addGap(163, 163, 163)
                .addComponent(jButtonAsignarTraslados)
                .addGap(92, 92, 92))
        );
        jPanelAdministradorLayout.setVerticalGroup(
            jPanelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdministradorLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistrarEmpresas)
                    .addComponent(jButtonRegistrarUsuarios)
                    .addComponent(jButtonAsignarTraslados))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelAdministrador);
        jPanelAdministrador.setBounds(20, 70, 650, 120);

        jPanelProductor.setBackground(new java.awt.Color(255, 255, 255));
        jPanelProductor.setMinimumSize(new java.awt.Dimension(650, 120));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Productor");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Registrar Residuos");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Solicitar Traslado");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Registrar Químicos");

        jButtonRegistrarResiduos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRegistrarResiduos.setText("Entrar");
        jButtonRegistrarResiduos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarResiduosActionPerformed(evt);
            }
        });

        jButtonRegistrarQuimicos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRegistrarQuimicos.setText("Entrar");
        jButtonRegistrarQuimicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarQuimicosActionPerformed(evt);
            }
        });

        jButtonRegistrarSolicitarTraslado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRegistrarSolicitarTraslado.setText("Entrar");
        jButtonRegistrarSolicitarTraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarSolicitarTrasladoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelProductorLayout = new javax.swing.GroupLayout(jPanelProductor);
        jPanelProductor.setLayout(jPanelProductorLayout);
        jPanelProductorLayout.setHorizontalGroup(
            jPanelProductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProductorLayout.createSequentialGroup()
                        .addGroup(jPanelProductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelProductorLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanelProductorLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(115, 115, 115)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(67, 67, 67))
                    .addGroup(jPanelProductorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRegistrarResiduos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRegistrarQuimicos)
                        .addGap(162, 162, 162)
                        .addComponent(jButtonRegistrarSolicitarTraslado)
                        .addGap(91, 91, 91))))
        );
        jPanelProductorLayout.setVerticalGroup(
            jPanelProductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistrarResiduos)
                    .addComponent(jButtonRegistrarQuimicos)
                    .addComponent(jButtonRegistrarSolicitarTraslado))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelProductor);
        jPanelProductor.setBounds(20, 190, 650, 130);

        jPanelTransporte.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Registrar Traslado");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Registrar Vehiculos");

        jButtonRegistrarTraslado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRegistrarTraslado.setText("Entrar");
        jButtonRegistrarTraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarTrasladoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setText("Empresa Transporte");

        jButtonRegistrarVehiculos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRegistrarVehiculos.setText("Entrar");
        jButtonRegistrarVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarVehiculosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTransporteLayout = new javax.swing.GroupLayout(jPanelTransporte);
        jPanelTransporte.setLayout(jPanelTransporteLayout);
        jPanelTransporteLayout.setHorizontalGroup(
            jPanelTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransporteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTransporteLayout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addContainerGap())
                    .addGroup(jPanelTransporteLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelTransporteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRegistrarTraslado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRegistrarVehiculos)
                        .addGap(70, 70, 70))
                    .addGroup(jPanelTransporteLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(41, 41, 41))))
        );
        jPanelTransporteLayout.setVerticalGroup(
            jPanelTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransporteLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistrarTraslado)
                    .addComponent(jButtonRegistrarVehiculos))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelTransporte);
        jPanelTransporte.setBounds(20, 320, 400, 120);

        jPanel6.setBackground(new java.awt.Color(153, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 450, 690, 60);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8);
        jPanel8.setBounds(0, 60, 690, 390);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Esconde la pantalla principal y abre la pantalla de Registrar Empresas
     *
     * @param evt Evento action perfomed del boton Registrar Empresas
     */
    private void jButtonRegistrarEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarEmpresasActionPerformed
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FRegistrarEmpresas p = FRegistrarEmpresas.getInstance();
                p.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        setVisible(true);
                    }
                });
                p.setVisible(true);
            }
        });
    }//GEN-LAST:event_jButtonRegistrarEmpresasActionPerformed
    /**
     * Crea 2 listas que contendran todas las empresas de transportes y las
     * solicitudes no atendidas respectivamente, comprobará si no hay nada
     * dentro de alguna de las 2 listas, si no hay nada entonces informará al
     * usuario de ello, en caso de que si tengan algo ambas listas esconderá la
     * pantalla y abrira la pantalla de RegistroAsignacionTraslado e
     * inicializará los botones y las tablas de dicha pantalla
     *
     * @param evt Evento action perfomed del boton Asignar Traslados
     */
    private void jButtonAsignarTrasladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsignarTrasladosActionPerformed
        List<Transporte> listaEmpresas = this.negocio.getEmpresasTransportes();
        List<Solicitud_de_Traslado> listaSolicitudes = this.negocio.consultarSolicitudesNoAtendidas();
        if ((listaEmpresas.isEmpty())) {
            this.mostrarMensajeError("No existen empresas transportadoras registradas.");
            return;
        }
        if (listaSolicitudes.isEmpty()) {
            this.mostrarMensajeError("No existen solicitudes registradas en proceso de conclusión.");
            return;
        }
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FRegistroAsignacionTraslado p = FRegistroAsignacionTraslado.getInstance();
                p.mostrarSolicitudesNoAtendidas(listaSolicitudes);
                p.setListaEmpresasT(null);
                p.setListaEmpresasT(listaEmpresas);
                p.botones();
                p.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        setVisible(true);
                    }
                });
                p.setVisible(true);
            }
        });
    }//GEN-LAST:event_jButtonAsignarTrasladosActionPerformed
    /**
     * Crea una lista con los químicos existentes, en caso de que la lista no
     * este vacia escondera la pantalla, abrira la pantalla de Registro Residuos
     * e inicializará el usuario y la lista de químicos, en caso de que no
     * existan químicos solo mandará un mensaje advirtiendo de ello
     *
     * @param evt Evento action perfomed del boton Registrar Residuos
     */
    private void jButtonRegistrarResiduosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarResiduosActionPerformed
        List<Quimico> quimicos = this.negocio.getQuimicos();
        if (!quimicos.isEmpty()) {
            this.setVisible(false);
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    FRegistroResiduos p = FRegistroResiduos.getInstance();
                    p.setUsuario(null);
                    p.setUsuario(usuarioR);
                    p.llenarListaQuimicos(quimicos);
                    p.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            setVisible(true);
                        }
                    });
                    p.setVisible(true);
                }
            });
        } else {
            this.mostrarMensajeError("No existen químicos agregados al sistema.");
        }

    }//GEN-LAST:event_jButtonRegistrarResiduosActionPerformed
    /**
     * Esconde la pantalla principal y abre la pantalla de Registrar Químicos
     *
     * @param evt Evento action perfomed del boton Registrar Quimicos
     */
    private void jButtonRegistrarQuimicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarQuimicosActionPerformed
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FRegistrarQuimicos p = FRegistrarQuimicos.getInstance();
                p.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        setVisible(true);
                    }
                });
                p.setVisible(true);
            }
        });
    }//GEN-LAST:event_jButtonRegistrarQuimicosActionPerformed
    /**
     * Comprobará que existan residuos creados por parte del productor, en caso
     * de que no sea así mostrará un mensaje advirtiendo de ello, en caso de que
     * si existan residuos escondera esta pantalla y abrirá la palabra de
     * Solicitar Traslado e inicializara el usuario y la lista de residuos
     *
     * @param evt Evento action perfomed del boton Registrar Solicitud Traslado
     */
    private void jButtonRegistrarSolicitarTrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarSolicitarTrasladoActionPerformed
        ObjectId idEmpresaProductora = ((Productor) this.usuarioR).getIdEmpresaProductora();
        List<Residuo> residuos = this.negocio.consultarResiduosProductor(idEmpresaProductora);
        if (!residuos.isEmpty()) {
            this.setVisible(false);
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    FSolicitudTraslado p = FSolicitudTraslado.getInstance();
                    p.setUsuario(null);
                    p.setUsuario(usuarioR);
                    p.llenarListaResiduos(residuos);
                    p.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            setVisible(true);
                        }
                    });
                    p.setVisible(true);
                }
            });
        } else {
            this.mostrarMensajeError("No existen residuos registrados por parte de la empresa productora a la que pertenece.");
        }


    }//GEN-LAST:event_jButtonRegistrarSolicitarTrasladoActionPerformed
    /**
     * Primero comprobara que existan aasignaciones de traslado para la empresa
     * en la que trabaja el usuario, si no existen mostrará un mensaje
     * advirtiendo de ello, si si existen, entonces esconderá esta pantalla y
     * abrirá la pantalla de Registro Traslado e inicializará al usuario y las
     * asignaciones
     *
     * @param evt Evento action perfomed del boton Registrar QTraslado
     */
    private void jButtonRegistrarTrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarTrasladoActionPerformed
        this.usuarioR = FabricaNegocios.crearFNegocio().getUsuario(2, usuarioR.getNombreUsuario(), usuarioR.getContrasena());
        ObjectId idEmpresaTransporte = ((Transportador) this.usuarioR).getIdEmpresaTransporte();
        List<Asignacion_Traslado> asignaciones = this.negocio.consultarAsignacionTrasladosEmpresaT(idEmpresaTransporte);

        if (asignaciones.isEmpty()) {
            this.mostrarMensajeError("No existen asignaciones de traslado para la empresa a la que pertenece.");
            return;
        }

        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FRegistroTraslado p = FRegistroTraslado.getInstance();
                p.setUsuario(null);
                p.setUsuario(usuarioR);
                p.mostrarAsignaciones(asignaciones);
                p.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        setVisible(true);
                    }
                });
                p.setVisible(true);
            }
        });

    }//GEN-LAST:event_jButtonRegistrarTrasladoActionPerformed
    /**
     * Esconde la pantalla principal y abre la pantalla de Registrar Vehículos e
     * inicializa el usuario
     *
     * @param evt Evento action perfomed del boton Registar Vehiculos
     */
    private void jButtonRegistrarVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarVehiculosActionPerformed

        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FRegistrarVehiculos p = FRegistrarVehiculos.getInstance();
                p.setUsuario(null);
                p.setUsuario(usuarioR);
                p.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        setVisible(true);

                    }
                });
                p.setVisible(true);
            }
        });

    }//GEN-LAST:event_jButtonRegistrarVehiculosActionPerformed
    /**
     * Esconde la pantalla principal y abre la pantalla de de RegistrarUsuarios
     *
     * @param evt Evento action perfomed del boton Registrar Usuarios
     */
    private void jButtonRegistrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarUsuariosActionPerformed
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FRegistrarUsuarios p = FRegistrarUsuarios.getInstance();
                p.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        setVisible(true);
                    }
                });
                p.setVisible(true);
            }
        });
    }//GEN-LAST:event_jButtonRegistrarUsuariosActionPerformed
    /**
     * Método para mostrar un mensaje de error
     *
     * @param mensaje Mensaje de error
     */
    public void mostrarMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje,
                "Error", JOptionPane.ERROR_MESSAGE);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAsignarTraslados;
    private javax.swing.JButton jButtonRegistrarEmpresas;
    private javax.swing.JButton jButtonRegistrarQuimicos;
    private javax.swing.JButton jButtonRegistrarResiduos;
    private javax.swing.JButton jButtonRegistrarSolicitarTraslado;
    private javax.swing.JButton jButtonRegistrarTraslado;
    private javax.swing.JButton jButtonRegistrarUsuarios;
    private javax.swing.JButton jButtonRegistrarVehiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelAdministrador;
    private javax.swing.JPanel jPanelProductor;
    private javax.swing.JPanel jPanelTransporte;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
